"""add document metadata

Revision ID: db5fd558109f
Revises: 8c8bc4c45628
Create Date: 2026-08-15 03:38:56.738683

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db5fd558109f'
down_revision: Union[str, Sequence[str], None] = '8c8bc4c45628'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chunks', sa.Column('chunking_version', sa.String(length=32), nullable=False))
    op.add_column('documents', sa.Column('department', sa.String(length=255), nullable=True))
    op.add_column('documents', sa.Column('year', sa.Integer(), nullable=True))
    op.add_column('documents', sa.Column('language', sa.String(length=16), nullable=True))
    op.add_column('documents', sa.Column('tags', sa.JSON(), nullable=False, server_default='[]'))
    op.create_index(op.f('ix_documents_department'), 'documents', ['department'], unique=False)
    op.create_index(op.f('ix_documents_language'), 'documents', ['language'], unique=False)
    op.create_index(op.f('ix_documents_year'), 'documents', ['year'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_documents_year'), table_name='documents')
    op.drop_index(op.f('ix_documents_language'), table_name='documents')
    op.drop_index(op.f('ix_documents_department'), table_name='documents')
    op.drop_column('documents', 'tags')
    op.drop_column('documents', 'language')
    op.drop_column('documents', 'year')
    op.drop_column('documents', 'department')
    op.drop_column('chunks', 'chunking_version')
    # ### end Alembic commands ###
