"""add chunk embeddings

Revision ID: f251a066246d
Revises: db5fd558109f
Create Date: 2026-08-15 21:23:41.966413

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector

# revision identifiers, used by Alembic.
revision: str = 'f251a066246d'
down_revision: Union[str, Sequence[str], None] = 'db5fd558109f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.create_table('chunk_embeddings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('chunk_id', sa.Integer(), nullable=False),
    sa.Column('embedding', Vector(768), nullable=False),
    sa.Column('model_name', sa.String(length=128), nullable=False),
    sa.Column('dimensions', sa.Integer(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['chunk_id'], ['chunks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint("chunk_id")
    )
    op.create_index(op.f('ix_chunk_embeddings_chunk_id'), 'chunk_embeddings', ['chunk_id'])
    op.add_column("chunks", sa.Column("indexed_at", sa.DateTime(timezone=True), nullable=True))
    op.execute("UPDATE chunks SET indexed_at = CURRENT_TIMESTAMP " "WHERE indexed_at IS NULL")
    op.alter_column("chunks", "indexed_at", existing_type=sa.DateTime(timezone=True), nullable=False)
    # ### end Alembic commands ###
    op.execute(
        "CREATE INDEX ix_chunk_embeddings_cosine_hnsw "
        "ON chunk_embeddings USING hnsw (embedding vector_cosine_ops)"
    )

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP INDEX IF EXISTS ix_chunk_embeddings_cosine_hnsw")
    op.drop_column('chunks', 'indexed_at')
    op.drop_index(op.f('ix_chunk_embeddings_chunk_id'), table_name='chunk_embeddings')
    op.drop_table('chunk_embeddings')
    # ### end Alembic commands ###
